### PR TITLE
implemented Job Location API endpoints

### PR DESCRIPTION
**Pull request by tspencer0917**
-Created files for Controller, Model, Repository, and Service.
-Implemented JobLocation class with "employer" and "address" attributes.
-Implemented Controller class for Job Location with request hanlders to CRUD JobLocation objects.
-Implemented associated Repository and Service classes to handle persistence to MySQL db.

### CODE REVIEW

**Review by lindskelsey — APPROVED** [review]
Looks good to me 🎉

**Review by angiedawn — APPROVED** [review]
I am still learning but it all looks good and workable to me.

**Review by adahathome — APPROVED** [review]
Nice! And wow, lombok really streamlines that getter and setter code <3

**Comment by adahathome** [comment]
lombok-getter-setter

I think you need these to make the getters and setters work?

**Comment by adahathome** [comment]
joblocation error
the "jobLocationService.get()" should be a ".getAll()". ".get()" takes an argument of a Long id, and returns a JobLocation object. ".getAll()" takes no argument and the return type matches the return type of your getter.

**Comment by lindskelsey** [comment]
> lombok-getter-setter
> 
> I think you need these to make the getters and setters work?

@ Data covers the getters and setters, https://projectlombok.org/features/Data

**Pull request merged**
