### PR TITLE
Client job association

### PR DESCRIPTION
**Pull request by adahathome**
Created a model to store associations between Clients and Job Locations.

Each association will be assigned a unique ID, and will have a Client ID and a Job Location ID.

Clients will be able to have many different jobs assigned, and Job Locations will be able to have many different Clients assigned.

Searches performed by Client ID will return all Job Locations for that Client, searches by Location ID will return all Clients for that Job Location.

### CODE REVIEW

**Review by PerceptualCells — APPROVED** [review]
As far as I can see this all makes sense. :)

**Review by tspencer0917 — APPROVED** [review]
Looks good to me.

**Comment by toinetteleigh** [comment]
Will look at all of this tonight

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Review by CherieLK — APPROVED** [review]
Looks good to me.

**Pull request merged**
